spring.application.name=personnage

spring.datasource.url=jdbc:postgresql://localhost:5432/personnage
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

role.user=ADMIN,USER,PDG

